/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YI62x1Hi81B
 */
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function InputForm() {
  return (
    <div key="1" className="w-full">
      <div className="w-full">
        <div
          className="w-full bg-white rounded-md shadow p-6"
          style={{
            width: "32rem",
          }}
        >
          <h1 className="text-2xl font-semibold mb-6">Create a new schema</h1>
          <form>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="prompt">
                Prompt
              </label>
              <Input id="prompt" placeholder="Describe the data you want to generate" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="negative-prompt">
                Negative Prompt
              </label>
              <Input id="negative-prompt" placeholder="A prompt that describes a situation in which the generate..." />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="data-sources">
                Data Sources
              </label>
              <Input id="data-sources" placeholder="users, orders" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="input-schema">
                Input Schema
              </label>
              <Textarea id="input-schema" placeholder="input schema" />
            </div>
            <div className="mb-4">
              <label className="block text-sm font-medium mb-1" htmlFor="output-schema">
                Output Schema
              </label>
              <Textarea id="output-schema" placeholder="output schema" />
            </div>
            <div className="flex justify-end mt-4">
              <Button className="mr-2" variant="outline">
                Cancel
              </Button>
              <Button>Create</Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
