/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZDz7rb2vlsQ
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"

export function VersionControl() {
  return (
    <div className="h-screen max-w-xs p-2 bg-white">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="text-lg font-semibold">History</h2>
        <Button className="text-sm" variant="ghost">
          «
        </Button>
      </div>
      <ScrollArea className="space-y-4">
        <Card className="w-full">
          <CardHeader>
            <CardTitle>v2</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between">
              <span className="text-sm">Added features</span>
              <span className="text-sm">3 days ago</span>
            </div>
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>v3</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between">
              <span className="text-sm">Bug fixes</span>
              <span className="text-sm">2 days ago</span>
            </div>
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>v4</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between">
              <span className="text-sm">Performance improvements</span>
              <span className="text-sm">1 day ago</span>
            </div>
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>v5</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between">
              <span className="text-sm">Updated documentation</span>
              <span className="text-sm">12 hours ago</span>
            </div>
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>v6</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between">
              <span className="text-sm">Refactored code</span>
              <span className="text-sm">8 hours ago</span>
            </div>
          </CardContent>
        </Card>
        
      </ScrollArea>
    </div>
  )
}
