/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IkstLL4Umpb
 */
import { Button } from "@/components/ui/button"

export function subs() {
  return (
    <div className="bg-[#F8F9FA] py-20">
      <div className="max-w-6xl mx-auto px-4">
        <h1 className="text-5xl font-bold text-center mb-6">Subscription Plan</h1>
        <p className="text-center text-lg mb-16">
          In publishing and graphic design, Lorem ipsum is a placeholder text commonly
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-white rounded-lg p-8 shadow-lg flex flex-col items-center">
            <ShieldCheckIcon className="text-[#FFA500] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Basic</h2>
            <p className="text-center mb-4">Ideal to Discover Amazon Sellers market get Started with outreach</p>
            <p className="mb-4">250 Leads</p>
            <p className="mb-6">Monthly: $190/month ($0.76 per lead)</p>
            <div className="text-3xl font-bold text-[#FFA500] mb-2">$1940</div>
            <div className="text-sm line-through text-gray-500 mb-6">$2280</div>
            <Button className="bg-[#FFA500] text-white">Purchase</Button>
          </div>
          <div className="bg-white rounded-lg p-8 shadow-xl flex flex-col items-center border-4 border-[#6C63FF]">
            <LightbulbIcon className="text-[#6C63FF] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Advanced</h2>
            <p className="text-center mb-4">
              Ideal to ramp up outreach to Amazon Seller Contacts for a single salesperson
            </p>
            <p className="mb-4">500 Leads</p>
            <p className="mb-6">Monthly: $350/month ($0.7 per lead)</p>
            <div className="text-3xl font-bold text-[#6C63FF] mb-2">$3570</div>
            <div className="text-sm line-through text-gray-500 mb-6">$4200</div>
            <Button className="bg-[#6C63FF] text-white">Purchase</Button>
          </div>
          <div className="bg-white rounded-lg p-8 shadow-lg flex flex-col items-center">
            <BriefcaseIcon className="text-[#00BFFF] mb-4 text-3xl" />
            <h2 className="text-2xl font-bold mb-4">Premium</h2>
            <p className="text-center mb-4">
              Ideal for the mid-to-large sales team that wants to scale Up their outreach to e-commerce Sellers
            </p>
            <p className="mb-4">1000 Leads</p>
            <p className="mb-6">Monthly: $650/month ($0.65 per lead)</p>
            <div className="text-3xl font-bold text-[#00BFFF] mb-2">$6630</div>
            <div className="text-sm line-through text-gray-500 mb-6">$7900</div>
            <Button className="bg-[#00BFFF] text-white">Purchase</Button>
          </div>
        </div>
      </div>
    </div>
  )
}


function ShieldCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function LightbulbIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}


function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}
